config/routes.rb
Rails.application.routes.draw do
  resources :articles do 
    resources :comments
  end
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :author
	has_many :comments
end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  	@authors = Author.all
  end

  def create
  	@article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def show
  		@article = Article.find(params[:id])
      @comments= @article.comments
  end

  def index
  		@articles = Article.all
  end

  private
	  def article_params
	    params.require(:article).permit(:title, :body, :author_id)
	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@article = Article.find(params[:article_id])
    @comment = Comment.new article_id: @article.id
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to articles_path
  end
  private
    def comment_params
      params.require(:comment).permit(:title, :body, :article_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.haml
%h1 Listing articles
 
%table.table
  %tr
    %th Author
    %th Title
    %th Text
    %th 
      %span.glyphicon.glyphicon-pencil
 
    - @articles.each_with_index do |article, index| 
      %tr
        %td= article.author.name
        %td= link_to article.title, article_path(article)
        %td= article.body
        %td= link_to 'Add Comment', new_article_comment_path(article)
 
= link_to 'New Article', new_article_path, class: 'btn btn-primary'

app/views/articles/new.html.haml
%h1 New Article
= form_for :article, url: articles_path do |f| 
	%p
		= f.label :author 
		%br
		= f.select(:author_id,  options_from_collection_for_select(@authors, :id, :name)) 

	%p
		= f.label :title  
		%br
		= f.text_field :title 

	%p
		= f.label :text 
		%br
		= f.text_area :body 

	%p
		= f.submit

app/views/articles/show.html.haml
%h1 Article:
%p
	%strong Author:
	= @article.author.name 

%p
	%strong Title:
	= @article.title
 
%p
	%strong Text:
	= @article.body

%p
	%h1 Comments:
	- @comments.each_with_index do |comment, index| 
		%h5= "#{index+1}.- " + comment.title
		.container= comment.body
	

app/views/comments/new.html.haml
%h1 
	= "New Comment for #{@article.title}"
= form_for @comment, url: article_comments_path do |f| 
	= f.hidden_field :article_id
	%p
		= f.label :title  
		%br
		= f.text_field :title 

	%p
		= f.label :text 
		%br
		= f.text_area :body 

	%p
		= f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home"></span></a>
	    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li class="active"><a href="/articles">Articles</a></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/welcome/index.html.haml
.jumbotron
	%h1 Welcome :)
	= link_to 'My Blog', {controller: 'articles'}, class: 'btn btn-primary'